import {
  Workflow,
  Bot,
  GitMerge,
  Users,
  Target,
  LifeBuoy,
  Database,
  FileText,
  Layers,
  Plug,
  Network,
  BarChart3,
  MessageCircle,
  Sparkles,
  Cloud,
  HeartPulse,
  Landmark,
  Building2,
  Truck,
  Factory,
  Megaphone,
  GraduationCap,
  ShoppingBag,
  Scale,
  HardHat,
  ConciergeBell,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const icons: Record<string, LucideIcon> = {
  workflow: Workflow,
  bot: Bot,
  "git-merge": GitMerge,
  users: Users,
  target: Target,
  "life-buoy": LifeBuoy,
  database: Database,
  "file-text": FileText,
  layers: Layers,
  plug: Plug,
  network: Network,
  "bar-chart-3": BarChart3,
  "message-circle": MessageCircle,
  sparkles: Sparkles,
  cloud: Cloud,
  "heart-pulse": HeartPulse,
  landmark: Landmark,
  "building-2": Building2,
  truck: Truck,
  factory: Factory,
  megaphone: Megaphone,
  "graduation-cap": GraduationCap,
  "shopping-bag": ShoppingBag,
  scale: Scale,
  "hard-hat": HardHat,
  "concierge-bell": ConciergeBell,
};

export default function Icon({ name, className }: { name: string; className?: string }) {
  const Comp = icons[name] ?? Sparkles;
  return <Comp className={cn("size-5", className)} strokeWidth={1.6} />;
}
